### ISSUE TITLE
Gyroscope and accelatormeter not working

### ISSUE THREAD

**Issue by Totallynotmwa** [PixelOS-AOSP/hardware_xiaomi#1]
Wth

**Comment by Totallynotmwa** [comment]
Also redmi note 9s mobile

**Comment by David112x** [comment]
Do you know the branch from where this issue comes from?

**Comment by Totallynotmwa** [comment]
> Do you know the branch from where this issue comes from?

I downloaded it off your website pixelos.net
The sensors doesnt get detected at all

**Comment by hridaya2004** [comment]
Wrong place to report the issue.

**Comment by Totallynotmwa** [comment]
> Wrong place to report the issue. @kawaaii 

Where do i report

**Comment by hridaya2004** [comment]
> Where do i report

https://t.me/pixeloschat

**Comment by Totallynotmwa** [comment]
> > Where do i report
> 
> https://t.me/pixeloschat

Ohh okay but i dont use telegram

**Comment by hridaya2004** [comment]
> Ohh okay but i dont use telegram

Create a account then?

**Comment by Totallynotmwa** [comment]
> > Ohh okay but i dont use telegram
> 
> Create a account then?

I prefer discord but i need the problem solved quickly i would

**Comment by hridaya2004** [comment]
> > > Ohh okay but i dont use telegram
> > 
> > 
> > Create a account then?
> 
> I prefer discord but i need the problem solved quickly i would

You are supposed to use XDA for these device specific issues.

**Comment by Totallynotmwa** [comment]
> > > > Ohh okay but i dont use telegram
> > > 
> > > 
> > > Create a account then?
> > 
> > 
> > I prefer discord but i need the problem solved quickly i would
> 
> You are supposed to use XDA for these device specific issues.

Ohh yeah am in their discord server but i was not in it before i made this post

**Comment by Totallynotmwa** [comment]
Closed bcs wrong area and dont need anymore
