### ISSUE TITLE
Mobile data connection problem

### ISSUE THREAD

**Issue by leonardospina** [PixelOS-AOSP/hardware_xiaomi#3]
Hi,
I have a Xiaomi Redmi Note 10 Pro and flashed the August release of PixelOS.
I always keep wifi and mobile data with roaming on, but I noticed that sometimes when I leave the home the mobile data connection does not work. I tried to turn it off, wait, and turn it on again but no success. The only way of getting it connected to the mobile data network seems to be a device reboot.

**Comment by hridaya2004** [comment]
Not something to report here.

**Comment by leonardospina** [comment]
what's the repo for this kind of issues?

**Comment by hridaya2004** [comment]
You can either contact the maintainer of your device in Telegram or open the issue in the device specific repository in PixelOS-Devices/your_device_repo.
